### ISSUE TITLE
Counting points correctly

### ISSUE THREAD

**Issue by nathanaelbosch** [nathbo/GO_DILab#11]
The territory/area counting is not completely right yet.

The case I'm thinking of is when there is a single **dead stone in the enemy territory**, it should probably count as captured by the enemy.

Bonus Idea: Implement some way of visually displaying the reasoning! I have some ideas there for how to do that in the console, maybe we could later add some of that to the GUI :)

**Comment by KarthikeyaKaushik** [comment]
Exactly! There's an easy solution from the image morphology pov I told you
about.
