### ISSUE TITLE
Adapt to different rulesets

### ISSUE THREAD

**Issue by nathanaelbosch** [nathbo/GO_DILab#2]
The ruleset is currently stored in self.rules.

Some things change depending on the ruleset:
- KO: I think we can just use the "A certain constellation should only appear once" rule, which is already implemented. This might lead to our bot thinking that moves are invalid even though he could play them, but the resulting generated move will be valid in both rulesets
- Area vs. Territory: That's quite straight forward, just if/else on the rules variable I guess :)

**Comment by nathanaelbosch** [comment]
Second part is implemented now! We still have to talk about Ko though :)

**Comment by liu-yushan** [comment]
It checks if there has been the same constellation before and puts out the warning, but the stone which cannot be captured is still removed from the board.

**Comment by nathanaelbosch** [comment]
Close enough, I think we shouldn't bother about perfectly implementing the different KO rules. We are a bit too restrictive right now, but any bot using our implementation will always play valid moves.
